# permissions for end users to view hnmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: capi-provider-hn
    app.kubernetes.io/managed-by: kustomize
  name: hnmachine-viewer-role
rules:
- apiGroups:
  - hn.appthrust.io
  resources:
  - hnmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hn.appthrust.io
  resources:
  - hnmachines/status
  verbs:
  - get
