---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hn.appthrust.io
  resources:
  - hnmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hn.appthrust.io
  resources:
  - hnmachines/finalizers
  verbs:
  - update
- apiGroups:
  - hn.appthrust.io
  resources:
  - hnmachines/status
  verbs:
  - get
  - patch
  - update
